
export const allergies = [...new Set([
    "Albumin",
    "Emulsifier",
    "Ovamucin",
    "Apovitellin",
    "Globulin",
    "Ovamucoid",
    "Binder",
    "Lecithin",
    "Ovoglobulin",
    "Coagulant",
    "Livetin",
    "Ovotransferrin",
    "Dried egg solids",
    "Lysozyme",
    "Ovovitelia",
    "Egg white",
    "Mayonnaise",
    "Ovovitellin",
    "Egg yellow",
    "Meringue",
    "Powdered egg",
    "Meringue powder",
    "Vitellin",
    "Eggnog",
    "Ovalbumin",
    "Whole egg",
    "Ammonium caseinate",
    "Dried milk",
    "Milk solids",
    "Artificial butter flavor",
    "Dry milk solids",
    "Natural flavoring",
    "Butter",
    "Fully cream milk powder",
    "Potassium caseinate",
    "Butter fat",
    "Ghee",
    "Rennet casein",
    "Buttermilk solids",
    "High protein flavor",
    "Sherbet",
    "Calcium caseinate",
    "Hydrolyzed casein",
    "Skim milk powder",
    "Caramel color",
    "Ice cream",
    "Sodium caseinate",
    "Caramel flavoring",
    "Ice milk",
    "Solids",
    "Casein",
    "Iron caseinate",
    "Sour cream",
    "Sour milk solids",
    "Cheese",
    "Lactoglobulin",
    "Whey",
    "Cream",
    "Curds",
    "Lactalbumin",
    "Whey powder",
    "Custards",
    "Lactose",
    "Whey protein concentrate",
    "Dairy product solids",
    "Magnesium caseinate",
    "Yogurt",
    "De-lactosed whey",
    "Milk derivative",
    "Yogurt powder",
    "Demineralized whey",
    "Milk protein",
    "Zinc caseinate",
    "Almond",
    "Filbert",
    "Nut butters",
    "Artificial nuts",
    "Gianduja",
    "Nutella",
    "Beechnut",
    "Ginkgo nut",
    "Pecan",
    "Brazil nut",
    "Hazelnut",
    "Pesto",
    "Bush nut",
    "Hickory nut",
    "Pili nut",
    "Butternut",
    "Lichee nut",
    "Pine nut",
    "Cashew",
    "Macadamia nut",
    "Pistachio",
    "Chestnut",
    "Marzipan",
    "Almond paste",
    "Praline",
    "Chinquapin nut",
    "Mashuga",
    "Shea nut",
    "Coconut",
    "Nangai nut",
    "Walnut",
    "Bulking agent",
    "Soy nuts",
    "Carob",
    "Soy panthenol",
    "Dofu",
    "Soy protein",
    "Edamame",
    "Soy sauce",
    "Emulsifier",
    "Soy sprouts",
    "Guar gum",
    "Soya",
    "Gum arabic",
    "Soya flour",
    "Hydrolyzed soy protein",
    "Soybean",
    "Hydrolyzed vegetable protein",
    "Soybean curd",
    "Kinnoko flour",
    "Soybean flour",
    "Kyodofu",
    "Soybean granules",
    "Lecithin",
    "Soybean oil",
    "Miso",
    "Soybean paste",
    "Msg",
    "Soybeans",
    "Natto",
    "Stabilizer",
    "Okara",
    "Starch",
    "Protein",
    "Supro",
    "Protein extender",
    "Tamari",
    "Shoyu sauce",
    "Tempeh",
    "Soy albumin",
    "Teriyaki sauce",
    "Soy bran",
    "Textured soy flour",
    "Soy concentrate",
    "Textured soy protein",
    "Soy fiber",
    "Textured vegetable protein",
    "Soy flour",
    "Thickener",
    "Soy formula",
    "Tofu",
    "Soy grits",
    "Vegetable broth",
    "Soy lecithin",
    "Vegetable gum",
    "Soy milk",
    "Vegetable starch",
    "Soy miso",
    "Yakidofu",
    "Soy nut butter",
    "Yuba",
    "All-purpose flour",
    "Kamut",
    "Bleached flour",
    "Malt",
    "Bran",
    "Malt extract",
    "Bread",
    "Matzo",
    "Bread crumbs",
    "Matzoh",
    "Bread flour",
    "Miller's bran",
    "Bromated flour",
    "Modified food starch",
    "Bulgur",
    "Modified starch",
    "Bulgur",
    "Msg",
    "Cake flour",
    "Protein",
    "Cereal extract",
    "Seitan",
    "Cornstarch",
    "Semolina",
    "Couscous",
    "Spelt",
    "Crackers",
    "Starch",
    "Durum flour",
    "Unbleached flour",
    "Durum wheat",
    "Vegetable gum",
    "Enriched flour",
    "Vegetable starch",
    "Farina",
    "Vital gluten",
    "Flour",
    "Wheat bran",
    "Gelatinized starch",
    "Wheat flour",
    "Germ",
    "Wheat germ",
    "Gluten",
    "Wheat gluten",
    "Graham flour",
    "Wheat starch",
    "Hard durum flour",
    "White flour",
    "High gluten flour",
    "Whole wheat",
    "High protein flour",
    "Whole wheat flour",
    "Hydrolyzed vegetable protein",
    "Barnacle",
    "Lobster",
    "Crab",
    "Moreton Bay Bugs",
    "Crawfish",
    "Prawns",
    "Crayfish",
    "Scampi",
    "Ecrevisse",
    "Seafood flavoring",
    "Fish stock",
    "Shrimp",
    "Krill",
    "Tomalley",
    "Langostine",
    "Imitation shellfish",
    "Langouste",
    "Arachic oil",
    "Arachis",
    "Arachis hypogaea",
    "Artificial nuts",
    "Beer nuts",
    "Boiled peanuts",
    "Cold pressed peanut oil",
    "Crushed nuts",
    "Crushed peanuts",
    "Dry roasted peanuts",
    "Earth nuts",
    "Emulsifier",
    "Expelled peanut oil",
    "Extruded peanut oil",
    "Goober peas",
    "Goobers",
    "Ground peanuts",
    "Ground nuts",
    "Hydrolyzed peanut protein",
    "Hypogaeic acid",
    "Mandelonas",
    "Marzipan",
    "Mixed nuts",
    "Mole sauce",
    "Monkey nuts",
    "Nougat",
    "Nu nuts",
    "Flavored nuts",
    "Nut pieces",
    "Nutmeat",
    "Oriental sauce",
    "Peanut",
    "Peanut butter",
    "Peanut flour",
    "Peanut paste",
    "Peanut sauce",
    "Peanut syrup",
    "Spanish peanuts",
    "Virginia peanuts",
    "Anchovies",
    "Barbeque sauce",
    "Bass",
    "Bouillabaise",
    "Caesar salad",
    "Caesar dressing",
    "Caponata",
    "Catfish",
    "Cod",
    "Flounder",
    "Grouper",
    "Haddock",
    "Hake",
    "Halibut",
    "Herring",
    "Imitation fish",
    "Mahi mahi",
    "Meatloaf",
    "Perch",
    "Pike",
    "Polluck",
    "Salmon",
    "Scrod",
    "Snapper",
    "Sole",
    "Surimi",
    "Swordfish",
    "Tilapia",
    "Trout",
    "Tuna",
    "Worcestershire sauce"
])]
